profile: local

application.name: yosep-mvc-boiler-plate-java

server:
  port: 10000
  logging:
    access: true
  shutdown: graceful

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      enable_lazy_load_no_trans: true
      jdbc:
        batch_size: 1000
        time_zone: Asia/Seoul

  datasource:
    hikari:
      max-lifetime: 100000
      maximum-pool-size: 10
    yosep-read:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:yosep;MODE=MySQL;DATABASE_TO_UPPER=false
      username: SA
      password:
    yosep-write:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:yosep;MODE=MySQL;DATABASE_TO_UPPER=false
      username: SA
      password:

#  sql:
#    init:
#      mode: embedded
#      schema-locations: classpath*:sql/h2-table-create.sql
#      data-locations: classpath*:sql/h2-dat  a-insert.sql